{{- /* Issue 1 */}}
{{- /* template "example.hpa" .Values.a.hpa */}}
{{- /* template "example.hpa" .Values.b.hpa */}}

{{- /* Issue 2 */}}
{{- /* range $key, $value := .Values }}
  {{- template "example.hpa" $value.hpa }}
{{- end */}}

{{- /* Bonus Issues */}}
{{ range .Values }}
  {{- template "example.hpa" .hpa }}
{{- end }}
